# Generated by Django 5.0.4 on 2024-05-05 07:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('FML', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfFinProduct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfStatus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeActiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfTypeActiv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewActiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfViewActiv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfViewClient', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('FML', models.TextField(blank=True, verbose_name='ФИО')),
                ('phone', models.IntegerField(blank=True, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='RequestClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfActiv', models.TextField()),
                ('NameOfClient', models.TextField()),
                ('sum', models.IntegerField()),
                ('term', models.IntegerField()),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.client')),
                ('id_FinProduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.finproduct')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
                ('id_TypeActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.typeactiv')),
                ('id_ViewActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewactiv')),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_sum', models.BigIntegerField()),
                ('max_term', models.BigIntegerField()),
                ('min_sum', models.BigIntegerField()),
                ('min_term', models.BigIntegerField()),
                ('id_FinProduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.finproduct')),
                ('id_Investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
                ('id_TypeActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.typeactiv')),
                ('id_ViewActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewactiv')),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='MySuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialConditions', models.TextField()),
                ('sum', models.IntegerField()),
                ('term', models.IntegerField()),
                ('id_RequestClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.requestclient')),
                ('id_RequestInvestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.requestinvestor')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
            ],
        ),
        migrations.CreateModel(
            name='LogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_changes', models.DateTimeField()),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.client')),
                ('id_Investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('id_MySuggestions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.mysuggestions')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
            ],
        ),
    ]
