# Generated by Django 5.0.4 on 2024-05-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id_RequestInvestor',
        ),
        migrations.AddField(
            model_name='answer',
            name='id_Investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invest.investor'),
        ),
    ]
