# Generated by Django 5.0.4 on 2024-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_remove_answer_id_requestinvestor_answer_id_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysuggestions',
            name='stavka',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
