# Generated by Django 5.0.4 on 2024-05-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_mysuggestions_stavka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysuggestions',
            name='id_RequestInvestor',
        ),
        migrations.AddField(
            model_name='mysuggestions',
            name='id_Investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.investor'),
        ),
    ]
