# Generated by Django 5.0.4 on 2024-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_requestclient_bankrotstvo_requestclient_pristav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclient',
            name='bankrotstvo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestclient',
            name='pristav',
            field=models.IntegerField(),
        ),
    ]
