# Generated by Django 5.0.4 on 2024-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='FML',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
