# Generated by Django 5.0.4 on 2024-05-06 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_alter_account_fml_alter_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_RequestClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invest.requestclient')),
                ('id_RequestInvestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invest.requestinvestor')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
            ],
        ),
    ]
