
ac1 = Account(email = "nick@mail.ru", FML = 'Nikita Sergeich', username = 'nick', phone = 88005553535)
ac1.set_password('55667788')
ac1.save()
ac2 = Account(email = "dima@mail.ru", FML = 'Dima Nikitovich', username = 'dima', phone = 88005553555)
ac2.set_password('55667788')
ac2.save()
ac3 = Account(email = "oleg@mail.ru", FML = 'Oleg Konstantinovich', username = 'oleg', phone = 88005553536)
ac3.set_password('55667788')
ac3.save()
#добавленно
ac4 = Account(email="ivan@mail.ru", FML='Ivan Sergeich', username='ivan', phone=88005553537)
ac4.set_password('55667788')
ac4.save()
ac5 = Account(email="michael@mail.ru", FML='Michael Mihailovich', username='michael', phone=88005553538)
ac5.set_password('55667788')
ac5.save()
ac6 = Account(email="alex@mail.ru", FML='Alex Dmityievich', username='alex', phone=88005553539)
ac6.set_password('55667788')
ac6.save()
ac7 = Account(email="sasha@mail.ru", FML='Sasha Alexseevich', username='sasha', phone=88005553540)
ac7.set_password('55667788')
ac7.save()
ac8 = Account(email="daniil@mail.ru", FML='Daniil Sergeich', username='daniil', phone=88005553541)
ac8.set_password('55667788')
ac8.save()
ac9 = Account(email="victor@mail.ru", FML='Victor Konstantinovich', username='victor', phone=88005553542)
ac9.set_password('55667788')
ac9.save()
ac10 = Account(email="nikolay@mail.ru", FML='Nikolay Mihailovich', username='nikolay', phone=88005553543)
ac10.set_password('55667788')
ac10.save()


vc1 = ViewClient(NameOfViewClient = "nick")
vc1.save()
vc2 = ViewClient(NameOfViewClient = "dima")
vc2.save()
vc3 = ViewClient(NameOfViewClient = "oleg")
vc3.save()
#добавленно
vc4 = ViewClient(NameOfViewClient = "ivan")
vc4.save()
vc5 = ViewClient(NameOfViewClient = "michael")
vc5.save()
vc6 = ViewClient(NameOfViewClient = "alex")
vc6.save()
vc7 = ViewClient(NameOfViewClient = "sasha")
vc7.save()
vc8 = ViewClient(NameOfViewClient = "daniil")
vc8.save()
vc9 = ViewClient(NameOfViewClient = "victor")
vc9.save()
vc10 = ViewClient(NameOfViewClient = "nikolay")
vc10.save()


st1 = Status(NameOfStatus = "Отказано")
st1.save()
st2 = Status(NameOfStatus = "Ожидает ответа")
st2.save()
st3 = Status(NameOfStatus = "Одобрена")
st3.save()



ta1 = TypeActiv(NameOfTypeActiv = "Недвижимость")
ta1.save()
ta2 = TypeActiv(NameOfTypeActiv = "Транспортное средство")
ta2.save()
ta3 = TypeActiv(NameOfTypeActiv = "Прицеп")
ta3.save()


fp1 = FinProduct(NameOfFinProduct = "Ипотека")
fp1.save()
fp2 = FinProduct(NameOfFinProduct = "Лизинг")
fp2.save()
fp3 = FinProduct(NameOfFinProduct = "Продажа")
fp3.save()


va1 = ViewActiv(NameOfViewActiv = "Недвижимость")
va1.save()
va2 = ViewActiv(NameOfViewActiv = "Движимость")
va2.save()
va3 = ViewActiv(NameOfViewActiv = "Инвестиция")
va3.save()


cl1 = Client(address = "ул.Мира д.7б кв226", FML = "Nikita Sergeich")
cl1.save()
cl2 = Client(address = "ул.Декабря д.7б кв326", FML = "Dima Nikitovich")
cl2.save()
cl3 = Client(address = "ул.Сентября д.7б кв2426", FML = "Oleg Nikitovich")
cl3.save()
#добавленно
cl4 = Client(address = "ул.Юрша д.92 кв226", FML = "Ivan Sergeich")
cl4.save()
cl5 = Client(address = "ул.Дружбы д.4 кв34", FML = "Michael Mihailovich")
cl5.save()
cl6 = Client(address = "ул.Пушкина д.11 кв26", FML = "Alex Dmityievich")
cl6.save()
cl7 = Client(address = "ул.Малкова д.10 кв22", FML = "Sasha Alexseevich")
cl7.save()
cl8 = Client(address = "ул.Революции д.59 кв39", FML = "Daniil Sergeich")
cl8.save()
cl9 = Client(address = "ул.Карбышева д.13а кв266", FML = "Victor Konstantinovich")
cl9.save()
cl10 = Client(address = "ул.Мира д.134 кв2", FML = "Nikolay Mihailovich")
cl10.save()


in1 = Investor(id_Account = ac1, id_ViewClient = vc1, name ="Пётр") 
in1.save()
in2 = Investor(id_Account = ac2, id_ViewClient = vc2, name ="Виктор")
in2.save()
in3 = Investor(id_Account = ac3, id_ViewClient = vc3, name ="Теодор")
in3.save()
#добавленно
in4 = Investor(id_Account=ac5, id_ViewClient=vc1, name="Алевтина")
in4.save()
in5 = Investor(id_Account=ac5, id_ViewClient=vc1, name="Илья")
in5.save()
in6 = Investor(id_Account=ac6, id_ViewClient=vc2, name="Алексей")
in6.save()
in7 = Investor(id_Account=ac7, id_ViewClient=vc3, name="Галина")
in7.save()
in8 = Investor(id_Account=ac8, id_ViewClient=vc1, name="Генадий")
in8.save()
in9 = Investor(id_Account=ac9, id_ViewClient=vc2, name="Виктор")
in9.save()
in10 = Investor(id_Account=ac10, id_ViewClient=vc3, name="Николай")
in10.save()


ri1 = RequestInvestor(id_FinProduct = fp1, id_Investor = in1, id_Status = st1, id_TypeActiv = ta1, id_ViewActiv = va1, id_ViewClient = vc1, max_sum = 1000, max_term = 10, min_sum = 1, min_term = 1)
ri1.save()
ri2 = RequestInvestor(id_FinProduct = fp2, id_Investor = in2, id_Status = st2, id_TypeActiv = ta2, id_ViewActiv = va2, id_ViewClient = vc2, max_sum = 2000, max_term = 20, min_sum = 2, min_term = 2)
ri2.save()
ri3 = RequestInvestor(id_FinProduct = fp3, id_Investor = in3, id_Status = st3, id_TypeActiv = ta3, id_ViewActiv = va3, id_ViewClient = vc3, max_sum = 3000, max_term = 30, min_sum = 3, min_term = 3)
ri3.save()
#добавленно
ri4 = RequestInvestor(id_FinProduct=fp2, id_Investor=in4, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=2500, max_term=25, min_sum=10, min_term=10)
ri4.save()
ri5 = RequestInvestor(id_FinProduct=fp2, id_Investor=in5, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=2500, max_term=25, min_sum=10, min_term=10)
ri5.save()
ri6 = RequestInvestor(id_FinProduct=fp3, id_Investor=in6, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, max_sum=3500, max_term=35, min_sum=15, min_term=15)
ri6.save()
ri7 = RequestInvestor(id_FinProduct=fp1, id_Investor=in7, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, max_sum=4500, max_term=45, min_sum=20, min_term=20)
ri7.save()
ri8 = RequestInvestor(id_FinProduct=fp2, id_Investor=in8, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=5500, max_term=55, min_sum=25, min_term=25)
ri8.save()
ri9 = RequestInvestor(id_FinProduct=fp3, id_Investor=in9, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, max_sum=6500, max_term=65, min_sum=30, min_term=30)
ri9.save()
ri10 = RequestInvestor(id_FinProduct=fp1, id_Investor=in10, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, max_sum=7500, max_term=75, min_sum=35, min_term=35)
ri10.save()

rc1 = RequestClient(id_FinProduct = fp2, id_Client = cl1, id_Status = st1, id_TypeActiv = ta1, id_ViewActiv = va1, id_ViewClient = vc1, NameOfActiv = "Car", NameOfClient = "dima", sum = 100000, term = 10)
rc1.save()
rc2 = RequestClient(id_FinProduct = fp3, id_Client = cl2, id_Status = st2, id_TypeActiv = ta2, id_ViewActiv = va2, id_ViewClient = vc2, NameOfActiv = "Gun", NameOfClient = "nick", sum = 200000, term = 20)
rc2.save()
rc3 = RequestClient(id_FinProduct = fp1, id_Client = cl3, id_Status = st3, id_TypeActiv = ta3, id_ViewActiv = va3, id_ViewClient = vc3, NameOfActiv = "Cat", NameOfClient = "oleg", sum = 300000, term = 30)
rc3.save()
#добавленно
rc4 = RequestClient(id_FinProduct = fp1, id_Client=cl4, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, NameOfActiv="Dog", NameOfClient="ivan", sum=400000, term=40)
rc4.save()
rc5 = RequestClient(id_FinProduct = fp3, id_Client=cl5, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, NameOfActiv="House", NameOfClient="michael", sum=500000, term=50)
rc5.save()
rc6 = RequestClient(id_FinProduct = fp2, id_Client=cl6, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, NameOfActiv="Car", NameOfClient="alex", sum=600000, term=60)
rc6.save()
rc7 = RequestClient(id_FinProduct = fp3, id_Client=cl7, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, NameOfActiv="Dog", NameOfClient="sasha", sum=700000, term=70)
rc7.save()
rc8 = RequestClient(id_FinProduct = fp1, id_Client=cl8, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, NameOfActiv="Cat", NameOfClient="daniil", sum=800000, term=80)
rc8.save()
rc9 = RequestClient(id_FinProduct = fp2, id_Client=cl9, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, NameOfActiv="Bird", NameOfClient="victor", sum=900000, term=90)
rc9.save()
rc10 = RequestClient(id_FinProduct = fp1, id_Client=cl10, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, NameOfActiv="Fish", NameOfClient="nikolay", sum=1000000, term=100)
rc10.save()


ms1 = MySuggestions(id_RequestClient = rc1, id_RequestInvestor = ri1, id_Status = st1, SpecialConditions = "None", sum = 100000, term = 10)
ms1.save()
ms2 = MySuggestions(id_RequestClient = rc2, id_RequestInvestor = ri2, id_Status = st2, SpecialConditions = "None", sum = 200000, term = 20)
ms2.save()
ms3 = MySuggestions(id_RequestClient = rc3, id_RequestInvestor = ri3, id_Status = st3, SpecialConditions = "text for test", sum = 300000, term = 30)
ms3.save()
#добавленно
ms4 = MySuggestions(id_RequestClient=rc4, id_RequestInvestor=ri4, id_Status=st3, SpecialConditions="None", sum=400000, term=40)
ms4.save()
ms5 = MySuggestions(id_RequestClient=rc5, id_RequestInvestor=ri5, id_Status=st1, SpecialConditions="None", sum=500000, term=50)
ms5.save()
ms6 = MySuggestions(id_RequestClient=rc6, id_RequestInvestor=ri6, id_Status=st2, SpecialConditions="None", sum=600000, term=60)
ms6.save()
ms7 = MySuggestions(id_RequestClient=rc7, id_RequestInvestor=ri7, id_Status=st3, SpecialConditions="None", sum=700000, term=70)
ms7.save()
ms8 = MySuggestions(id_RequestClient=rc8, id_RequestInvestor=ri8, id_Status=st1, SpecialConditions="None", sum=800000, term=80)
ms8.save()
ms9 = MySuggestions(id_RequestClient=rc9, id_RequestInvestor=ri9, id_Status=st2, SpecialConditions="text for test", sum=900000, term=90)
ms9.save()
ms10 = MySuggestions(id_RequestClient=rc10, id_RequestInvestor=ri10, id_Status=st3, SpecialConditions="text for test", sum=1000000, term=100)
ms10.save()

ls1 = LogStatus(id_Investor = in1, id_Status = st1, id_MySuggestions = ms1, id_Client = cl1, time_changes = '2023-4-23 10:21:35')
ls1.save()
ls2 = LogStatus(id_Investor = in2, id_Status = st2, id_MySuggestions = ms2, id_Client = cl2, time_changes = '2024-5-6 12:31:52')
ls2.save()
ls3 = LogStatus(id_Investor = in3, id_Status = st3, id_MySuggestions = ms3, id_Client = cl3, time_changes = '2023-2-12 15:28:11')
ls3.save()
#добавленно
ls4 = LogStatus(id_Investor=in4, id_Status=st3, id_MySuggestions=ms4, id_Client=cl4, time_changes='2023-3-15 16:45:30')
ls4.save()
ls5 = LogStatus(id_Investor=in5, id_Status=st1, id_MySuggestions=ms5, id_Client=cl5, time_changes='2023-4-24 17:30:45')
ls5.save()
ls6 = LogStatus(id_Investor=in6, id_Status=st2, id_MySuggestions=ms6, id_Client=cl6, time_changes='2023-5-7 18:45:30')
ls6.save()
ls7 = LogStatus(id_Investor=in7, id_Status=st3, id_MySuggestions=ms7, id_Client=cl7, time_changes='2023-6-18 19:30:15')
ls7.save()
ls8 = LogStatus(id_Investor=in8, id_Status=st1, id_MySuggestions=ms8, id_Client=cl8, time_changes='2023-7-9 20:15:00')
ls8.save()
ls9 = LogStatus(id_Investor=in9, id_Status=st2, id_MySuggestions=ms9, id_Client=cl9, time_changes='2023-8-20 21:00:45')
ls9.save()
ls10 = LogStatus(id_Investor=in10, id_Status=st3, id_MySuggestions=ms10, id_Client=cl10, time_changes='2023-9-21 22:00:30')
ls10.save()





ri3 = RequestInvestor(id_FinProduct = fp3, id_Investor = in2, id_Status = st3, id_TypeActiv = ta3, id_ViewActiv = va3, id_ViewClient = vc3, max_sum = 3000000, max_term = 30, min_sum = 3, min_term = 3)
ri3.save()
#добавленно
ri4 = RequestInvestor(id_FinProduct=fp2, id_Investor=in2, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=2500000, max_term=25, min_sum=10, min_term=10)
ri4.save()
ri5 = RequestInvestor(id_FinProduct=fp2, id_Investor=in2, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=2500000, max_term=25, min_sum=10, min_term=10)
ri5.save()
ri6 = RequestInvestor(id_FinProduct=fp3, id_Investor=in2, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, max_sum=35000000, max_term=35, min_sum=15, min_term=15)
ri6.save()
ri7 = RequestInvestor(id_FinProduct=fp1, id_Investor=in2, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, max_sum=4500, max_term=45, min_sum=20, min_term=20)
ri7.save()
ri8 = RequestInvestor(id_FinProduct=fp2, id_Investor=in2, id_Status=st1, id_TypeActiv=ta1, id_ViewActiv=va1, id_ViewClient=vc1, max_sum=5500, max_term=55, min_sum=25, min_term=25)
ri8.save()
ri9 = RequestInvestor(id_FinProduct=fp3, id_Investor=in2, id_Status=st2, id_TypeActiv=ta2, id_ViewActiv=va2, id_ViewClient=vc2, max_sum=6500, max_term=65, min_sum=30, min_term=30)
ri9.save()
ri10 = RequestInvestor(id_FinProduct=fp1, id_Investor=in2, id_Status=st3, id_TypeActiv=ta3, id_ViewActiv=va3, id_ViewClient=vc3, max_sum=7500, max_term=75, min_sum=35, min_term=35)
ri10.save()