# Generated by Django 5.0.4 on 2024-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('FML', models.TextField()),
                ('login', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
