# Generated by Django 5.0.4 on 2024-05-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('FML', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfFinProduct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfStatus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeActiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfTypeActiv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewActiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfViewActiv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfViewClient', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.account')),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='RequestClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfActiv', models.TextField()),
                ('NameOfClient', models.TextField()),
                ('sum', models.IntegerField()),
                ('term', models.IntegerField()),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.client')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
                ('id_TypeActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.typeactiv')),
                ('id_ViewActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewactiv')),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_sum', models.BigIntegerField()),
                ('max_term', models.BigIntegerField()),
                ('min_sum', models.BigIntegerField()),
                ('min_term', models.BigIntegerField()),
                ('id_FinProduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.finproduct')),
                ('id_Investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
                ('id_TypeActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.typeactiv')),
                ('id_ViewActiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewactiv')),
                ('id_ViewClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.viewclient')),
            ],
        ),
        migrations.CreateModel(
            name='MySuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialConditions', models.TextField()),
                ('sum', models.IntegerField()),
                ('term', models.IntegerField()),
                ('id_RequestClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.requestclient')),
                ('id_RequestInvestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.requestinvestor')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
            ],
        ),
        migrations.CreateModel(
            name='LogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_changes', models.DateTimeField()),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.client')),
                ('id_Investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('id_MySuggestions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.mysuggestions')),
                ('id_Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.status')),
            ],
        ),
    ]
